import './globals.css'
import { Montserrat, Open_Sans } from "next/font/google"
import AppContextProvider from '@/context/AppContext'

export const metadata = {
  title: 'History Verse',
  description: 'Generated by create next app',
}


const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

const open_sans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open_sans",
  weight: ['300', '400', '500', '600', '700', '800']
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={` ${montserrat.variable} ${open_sans.variable} `
    }>
      <body>
        <AppContextProvider>
          {children}
        </AppContextProvider>

      </body>
    </html>
  )
}
